### ISSUE TITLE
Subir App

### ISSUE THREAD

**Issue by JMER15** [mriadev/Tarea-4.13.-Practica6.-Git.-Issues#1]
María añade al repositorio la app de Gestisimal completa. Saludos!!!!!
@lmagarin

**Comment by mriadev** [comment]
Hecho!

**Comment by lmagarin** [comment]
Hola a ambos @mriadev @JMER15 . 
Algo falla porque no veo el enlace del código...

**Comment by JMER15** [comment]
María añade al repositorio el proyecto  "Gestisimal" completo. Falta documentar los paquetes y las excepciones. Saludos!!!!!
@lmagarin
