### ISSUE TITLE
documentación de atributos??

### ISSUE THREAD

**Issue by lmagarin** [mriadev/Tarea-4.13.-Practica6.-Git.-Issues#3]
Hola @mriadev @JMER15 
No veo la documentación del atributo ArrayList?? 
¿Has documentado algún atributo??

**Comment by mriadev** [comment]
https://github.com/mriadev/Tarea-4.13.-Practica6.-Git.-Issues/blob/f1be9d67d6374bb431fbdfcfb0386e7e53ee224b/src/gestisimal/business/Warehouse.java#L22

Los tengo puestos pero no sé por qué no me aparecen en la documentación

**Comment by lmagarin** [comment]
Al generar la documentación tienes que indicar que genere la documentación de los miembros privados (private)
